# Generated by Django 4.1.3 on 2023-02-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_alter_user_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=255)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.IntegerField(max_length=15)),
                ('contract_period', models.IntegerField(max_length=2)),
            ],
        ),
    ]
