# Generated by Django 4.1.7 on 2023-02-24 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.TimeField(choices=[(1, '9:00'), (2, '11:00'), (3, '1:00'), (4, '3:00'), (5, '5:00'), (6, '7:00'), (7, '9:00')], max_length=1)),
                ('status', models.BooleanField(default=False)),
                ('women', models.ForeignKey(limit_choices_to={'user_type': 'W'}, on_delete=django.db.models.deletion.CASCADE, related_name='Women', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('women', 'date'), name='unique_booking'),
        ),
    ]
